FROM python:3.12-alpine as builder

RUN pip3 install pipenv
RUN apk add --no-cache git

WORKDIR /app

COPY . .

RUN git reset --hard d4bf1a385df86253632926f746389eda81676c81
RUN pipenv install --system --deploy

ENTRYPOINT ["python3", "main.py"]